### ISSUE TITLE
Fix API inconsistencies

### ISSUE THREAD

**Issue by stefsmeets** [hpgem/nanomesh#113]
The API is currently a bit inconsistent, i.e.

### Mesher2D / Mesher3d:

- [x] `.contours` attribute -> #114 
- [x] Labels are not used on Mesher3D -> #114 
    - Get rid of `wrapped_contours`
    - `.contours` -> `.contour`
- [x] Can we also get rid of labels in Mesher2D? -> #114
- [x] Sort out how region attributes are passed to tetragonalize -> Fine the way it is for now, added a parameter to generate `region_markers` on the fly in #114 .

**Comment by stefsmeets** [comment]
Closes with #114
