### ISSUE TITLE
Plotting enhancements

### ISSUE THREAD

**Issue by stefsmeets** [hpgem/nanomesh#197]
Some ideas for plotting enhancements:

- [x] Color by label or by field -> #217 
- [x] Plot by label (keyword to select label) -> #219 
- [x] `show` (default plot), `plot`: customization -> #213 
- [x] Green / blue are terrible defaults for meshes (prefer higher contrast) -> #181
