### ISSUE TITLE
Fix issues with dashboard

### ISSUE THREAD

**Issue by stefsmeets** [hpgem/nanomesh#275]
This PR tracks issues with the dasbhoards:

- [x] Add nanomesh as a dependency to requirements -> #276
- [x] Deployed version needs new release of nanomesh (0.8.0)
- [x] Update documentation / readme to link to dashboards -> #276 
- [x] Update manifest.in -> #278
- [x] Move dashboards to own repo
- [x] Pin all versions

**Comment by stefsmeets** [comment]
Moving to hpgem/nanomesh-dashboards:
- `dash` directory
- `packages.txt`
- Update links in docs/index.rst
- Update links in readme.md
- Update links in Streamlit Cloud
